main: pl.bartixen.bxteam.Main
version: 4.0.1
author: Bartixen
name: BxTeam
api-version: '1.20'
website: https://bartixen.pl
description: Team

commands:
  team:
    description: Show team
  teamy:
    description: Show team
  bxteam:
    description: Info plugin