main: pl.bartixen.bxteam.Main
version: 3.1
author: Bartixen
name: BxTeam
api-version: '1.20'
website: https://bartixen.pl
description: Teamy

commands:
  team:
    description: Wyswietla teamy
  teamy:
    description: Wyswietla teamy
  bxteam: