main: pl.bartixen.bxteam.Main
version: 2.4
author: Bartixen
name: BxTeam
api-version: 1.17
website: https://bartixen.pl
description: Teamy

commands:
  team:
    description: Wyswietla teamy
  teamy:
    description: Wyswietla teamy
  bxteam: